### ISSUE TITLE
Error during npm install

### ISSUE THREAD

**Issue by chrisgorgo** [MRN-Code/nodeapi#51]
```
npm ERR! Darwin 15.2.0
npm ERR! argv "/usr/local/Cellar/node/5.3.0/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v5.3.0
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE

npm ERR! bcrypt@0.8.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bcrypt@0.8.5 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the bcrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls bcrypt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/filo/drive/workspace/nodeapi/npm-debug.log
```

**Comment by cdaringe** [comment]
@chrisfilo, a couple of our _X_-crypt dependencies (bcrypt included), pin us into specific versions of nodejs.  this is because during the install process, native addons are compiled (generally from c++) to expose javascript hooks to those packages.  I believe that iojs versions 2.4.0/2.5.0 both work right out of the box for `nodeapi`.  which nodejs version are you running?

the team will be migrating to track with nodejs LTS, which is currently 4.2.3.  if you'd care to use that, you may, but must update mcrypt to the latest `npm remove --save mcrypt && npm i mcrypt --save`.  ideally, we'd like node-version agnostic packages, but the `nodeapi` squad has not yet needed to dial that in.

HTH

@dylancwood @rsskmr, some README tidy is probably in order.  not sure what the BE team has been hackin' on back here recently.

**Comment by chrisgorgo** [comment]
I'm using nodejs 5.3, I'll try 4.2.3.

I have to admit that installation instructions are a bit confusing...

**Comment by cdaringe** [comment]
> I have to admit that installation instructions are a bit confusing...

agreed.  By this point they have been primarily for internal consumption.  you're the first non-COINSer to even try

**Comment by cdaringe** [comment]
ps, 5.3 works too, but the mcrypt swap above is still required

**Comment by chrisgorgo** [comment]
I've tried nodejs 4.2, but it's not python3 compatible. 

```
gyp ERR! configure error
gyp ERR! stack Error: Python executable "python" is v3.5.1, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at failPythonVersion (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:121:14)
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:110:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:204:7)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:818:16)
gyp ERR! stack     at Socket.<anonymous> (internal/child_process.js:319:11)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! stack     at Socket.emit (events.js:169:7)
gyp ERR! stack     at Pipe._onclose (net.js:469:12)
gyp ERR! System Darwin 15.2.0
gyp ERR! command "/usr/local/Cellar/node4-lts/4.2.4/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
gyp ERR! cwd /Users/filo/drive/workspace/nodeapi/node_modules/mcrypt
gyp ERR! node -v v4.2.4
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
```

I'll try the mcrypt swap...

Is there an easier installation route intended for normal users I am missing?

**Comment by cdaringe** [comment]
classic Python3.  Out-of-left field.  i wonder what the [systems bible](http://www.amazon.com/The-Systems-Bible-Beginners-Guide/dp/0961825170) has to say about this.

there is no magic or shortcut.  it's just very early software.  we all have 2.7 on our machines, and weren't aware that node-gyp was locked onto 2.x.  perhaps a `venv` would help, or using the `--python` flag onto the `npm` command would do it.  `npm` doesn't have it documented, but it does pass some args from its CLI to the node-gyp CLI.

what are your goals from getting all of this up and running?
